name: "Terraform GitHub Action for Pull Requests"
on:
  pull_request:
    branches: [test, dev, qa, prod, main]
env:
  tf_version: "latest"
  tf_working_dir: "."
  TF_WORKSPACE: ${{ github.base_ref }}
jobs:
  checkov:
    name: checkov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          token: ${{ secrets.ENGINEERING_GITHUB_PERSONAL_ACCESS_TOKEN }}
      - name: checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          download_external_modules: true